<?php

namespace App\Service;

/**
 * Drives the 5-question oral placement test (TP "test de niveau"): a fixed
 * script of increasingly demanding prompts (present tense -> narrative past
 * -> opinion/conditional -> reflection), scripted rather than generated by a
 * real LLM. No real audio capture yet either - the frontend sends typed
 * text, same as VoiceService. Whisper/GPT-4o wiring replaces the innards of
 * both services in a later chapter without changing the controllers' contract.
 */
final class PlacementTestService
{
    private const QUESTIONS = [
        "Hi! Let's start easy: what's your name, and where are you from?",
        'Nice to meet you! Can you tell me about your daily routine? What do you usually do in the morning?',
        'What did you do last weekend? Tell me about something fun you did recently.',
        'If you could change one thing about your city, what would it be, and why?',
        "Describe a challenge you've faced and how you dealt with it. What did you learn from it?",
    ];

    public function totalQuestions(): int
    {
        return \count(self::QUESTIONS);
    }

    public function openingMessage(): string
    {
        return "Hello! I'm your LinguaBot examiner. We're going to have a short conversation, ".
            "about 3 to 5 minutes - just answer naturally, there's no wrong answer. ".
            self::QUESTIONS[0];
    }

    /**
     * @param int $answeredCount how many questions the learner has already answered
     */
    public function nextQuestion(int $answeredCount): ?string
    {
        return self::QUESTIONS[$answeredCount] ?? null;
    }

    public function closingMessage(): string
    {
        return "Great, thank you! That's the end of the test - let's see your result.";
    }

    /**
     * Simulated CEFR placement heuristic: real proficiency scoring (grammar,
     * pronunciation, relevance) arrives with the GPT-4o integration. Until
     * then, level is estimated from a single surface signal - how many words
     * the learner uses per answer on average - which correlates loosely with
     * fluency and is enough to place a beginner differently from a fluent
     * speaker.
     *
     * @param string[] $userAnswers
     */
    public function evaluateLevel(array $userAnswers): string
    {
        if ([] === $userAnswers) {
            return 'A0';
        }

        $totalWords = 0;
        foreach ($userAnswers as $answer) {
            $totalWords += \count(preg_split('/\s+/', trim($answer), -1, PREG_SPLIT_NO_EMPTY));
        }
        $avgWordsPerAnswer = $totalWords / \count($userAnswers);

        return match (true) {
            $avgWordsPerAnswer < 4 => 'A0',
            $avgWordsPerAnswer < 8 => 'A1',
            $avgWordsPerAnswer < 14 => 'A2',
            $avgWordsPerAnswer < 22 => 'B1',
            default => 'B2',
        };
    }
}
