<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Daily challenge schema: daily_challenges, challenge_sessions.
 *
 * Hand-aligned on the validated MPD from Jalon 3 (§5.5).
 */
final class Version20260904150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Daily challenge: daily_challenges, challenge_sessions (Jalon 3 MPD §5.5)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE daily_challenges (
                id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                level_id        SMALLINT     NOT NULL REFERENCES levels(id),
                title           VARCHAR(200) NOT NULL,
                context         TEXT         NOT NULL,
                objective       TEXT         NOT NULL,
                keywords        JSONB        NOT NULL,
                character_name  VARCHAR(100) NOT NULL,
                challenge_date  DATE         NOT NULL,
                generated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
                UNIQUE (level_id, challenge_date)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_daily_challenges_date ON daily_challenges(challenge_date DESC)');
        $this->addSql('CREATE INDEX idx_daily_challenges_level_id ON daily_challenges(level_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE challenge_sessions (
                id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id         BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                challenge_id    BIGINT      NOT NULL REFERENCES daily_challenges(id),
                session_id      BIGINT      REFERENCES sessions(id),
                xp_earned       INTEGER     NOT NULL DEFAULT 0,
                completed_at    TIMESTAMPTZ,
                UNIQUE (user_id, challenge_id)
            )
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE challenge_sessions');
        $this->addSql('DROP TABLE daily_challenges');
    }
}
