<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Email verification flow: pending_registrations holds a registration's data
 * until the verification link is clicked, at which point a real row in
 * `users` is created and this one is deleted. Not part of the original
 * Jalon 3 MPD - added afterwards to support mandatory email verification.
 */
final class Version20260907090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Email verification: pending_registrations';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE pending_registrations (
                id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email          VARCHAR(255) NOT NULL,
                prenom         VARCHAR(100) NOT NULL,
                nom            VARCHAR(100) NOT NULL,
                password_hash  VARCHAR(255) NOT NULL,
                token          VARCHAR(64)  NOT NULL,
                expires_at     TIMESTAMPTZ  NOT NULL,
                created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_pending_registrations_email ON pending_registrations(email)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pending_registrations_token ON pending_registrations(token)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE pending_registrations');
    }
}
