<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Quiz A0 schema: quiz_modules, quiz_questions, quiz_attempts.
 *
 * Hand-aligned on the validated MPD from Jalon 3 (§5.4), same discipline as
 * the milestone 1 migration: `passed` is a native GENERATED ALWAYS AS STORED
 * column so it can never drift from `score` (RG09).
 */
final class Version20260904120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Quiz A0: quiz_modules, quiz_questions, quiz_attempts (Jalon 3 MPD §5.4)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE quiz_modules (
                id              SMALLINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                code            VARCHAR(20) NOT NULL UNIQUE,
                title           VARCHAR(100) NOT NULL,
                order_num       SMALLINT    NOT NULL UNIQUE,
                question_count  SMALLINT    NOT NULL DEFAULT 10 CHECK (question_count > 0),
                is_active       BOOLEAN     NOT NULL DEFAULT true
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE quiz_questions (
                id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                module_id       SMALLINT     NOT NULL REFERENCES quiz_modules(id),
                question_text   TEXT         NOT NULL,
                correct_answer  VARCHAR(200) NOT NULL,
                order_num       SMALLINT     NOT NULL,
                UNIQUE (module_id, order_num)
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE quiz_attempts (
                id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id         BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                module_id       SMALLINT    NOT NULL REFERENCES quiz_modules(id),
                score           SMALLINT    NOT NULL CHECK (score BETWEEN 0 AND 10),
                passed          BOOLEAN     NOT NULL GENERATED ALWAYS AS (score >= 7) STORED,
                xp_earned       INTEGER     NOT NULL DEFAULT 0 CHECK (xp_earned >= 0),
                attempted_at    TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            SQL);
        $this->addSql('CREATE INDEX idx_quiz_attempts_user_id ON quiz_attempts(user_id)');
        $this->addSql('CREATE INDEX idx_quiz_attempts_module_id ON quiz_attempts(module_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE quiz_attempts');
        $this->addSql('DROP TABLE quiz_questions');
        $this->addSql('DROP TABLE quiz_modules');
    }
}
