<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Admin logs schema (Jalon 3 MPD §5.6). Deletion of an admin account is
 * blocked (default RESTRICT, no ON DELETE clause) while their logs exist.
 */
final class Version20260904160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Admin logs: admin_logs (Jalon 3 MPD §5.6)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE admin_logs (
                id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                admin_id     BIGINT       NOT NULL REFERENCES users(id),
                action       VARCHAR(100) NOT NULL,
                target_type  VARCHAR(50),
                target_id    BIGINT,
                details      JSONB,
                created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
            )
            SQL);
        $this->addSql('CREATE INDEX idx_admin_logs_admin_id ON admin_logs(admin_id)');
        $this->addSql('CREATE INDEX idx_admin_logs_created_at ON admin_logs(created_at DESC)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE admin_logs');
    }
}
