<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Gamification schema: badges, user_badges, trophies, user_trophies.
 *
 * Hand-aligned on the validated MPD from Jalon 3 (§5.6), same discipline as
 * the earlier milestone migrations.
 */
final class Version20260904140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Gamification: badges, user_badges, trophies, user_trophies (Jalon 3 MPD §5.6)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TYPE trophy_rarity AS ENUM ('bronze', 'silver', 'gold', 'platinum')");

        $this->addSql(<<<'SQL'
            CREATE TABLE badges (
                id               SERIAL       PRIMARY KEY,
                code             VARCHAR(50)  NOT NULL UNIQUE,
                name             VARCHAR(100) NOT NULL,
                description      TEXT,
                icon             VARCHAR(100),
                condition_type   VARCHAR(50)  NOT NULL,
                condition_value  INTEGER      NOT NULL CHECK (condition_value >= 0),
                xp_bonus         INTEGER      NOT NULL DEFAULT 0,
                is_active        BOOLEAN      NOT NULL DEFAULT true
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE user_badges (
                id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                badge_id    INTEGER     NOT NULL REFERENCES badges(id),
                earned_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
                UNIQUE (user_id, badge_id)
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE trophies (
                id               SERIAL          PRIMARY KEY,
                code             VARCHAR(50)     NOT NULL UNIQUE,
                name             VARCHAR(100)    NOT NULL,
                description      TEXT,
                condition_type   VARCHAR(50)     NOT NULL,
                condition_value  INTEGER         NOT NULL,
                xp_reward        INTEGER         NOT NULL DEFAULT 0,
                rarity           trophy_rarity   NOT NULL DEFAULT 'bronze'
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE user_trophies (
                id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id           BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                trophy_id         INTEGER     NOT NULL REFERENCES trophies(id),
                progress_current  INTEGER     NOT NULL DEFAULT 0,
                progress_total    INTEGER     NOT NULL,
                earned_at         TIMESTAMPTZ,
                UNIQUE (user_id, trophy_id),
                CHECK (progress_current <= progress_total),
                CHECK (progress_total > 0),
                CHECK (progress_current >= 0)
            )
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE user_trophies');
        $this->addSql('DROP TABLE trophies');
        $this->addSql('DROP TABLE user_badges');
        $this->addSql('DROP TABLE badges');
        $this->addSql('DROP TYPE trophy_rarity');
    }
}
