<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Milestone 1 schema: levels, users, scenarios, sessions, session_messages.
 *
 * Hand-aligned on the validated MPD from Jalon 3 (PostgreSQL native ENUM
 * types, CHECK constraints, partial/descending indexes) rather than the
 * plain diff Doctrine generates from the entity mapping.
 */
final class Version20260904092825 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Milestone 1: levels, users, scenarios, sessions, session_messages (Jalon 3 MPD)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TYPE user_role AS ENUM ('ROLE_USER', 'ROLE_ADMIN')");
        $this->addSql("CREATE TYPE session_status AS ENUM ('in_progress', 'completed', 'abandoned')");
        $this->addSql("CREATE TYPE message_role AS ENUM ('user', 'assistant')");
        $this->addSql("CREATE TYPE scenario_category AS ENUM ('quotidien', 'thematique')");

        $this->addSql(<<<'SQL'
            CREATE TABLE levels (
                id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code VARCHAR(5) NOT NULL UNIQUE,
                name VARCHAR(80) NOT NULL,
                description TEXT,
                xp_threshold INTEGER NOT NULL CHECK (xp_threshold >= 0),
                order_num SMALLINT NOT NULL UNIQUE CHECK (order_num BETWEEN 0 AND 9)
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                prenom VARCHAR(100) NOT NULL,
                nom VARCHAR(100) NOT NULL,
                email VARCHAR(255) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                role user_role NOT NULL DEFAULT 'ROLE_USER',
                level_id SMALLINT NOT NULL REFERENCES levels(id) ON DELETE RESTRICT ON UPDATE CASCADE,
                total_xp INTEGER NOT NULL DEFAULT 0 CHECK (total_xp >= 0),
                sessions_count INTEGER NOT NULL DEFAULT 0 CHECK (sessions_count >= 0),
                avg_score NUMERIC(5, 2) CHECK (avg_score BETWEEN 0 AND 100),
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ,
                is_active BOOLEAN NOT NULL DEFAULT true,
                deleted_at TIMESTAMPTZ DEFAULT NULL
            )
            SQL);
        $this->addSql('CREATE INDEX idx_users_email ON users(email)');
        $this->addSql('CREATE INDEX idx_users_level_id ON users(level_id)');
        $this->addSql('CREATE INDEX idx_users_is_active ON users(is_active) WHERE is_active = true');

        $this->addSql(<<<'SQL'
            CREATE TABLE scenarios (
                id SERIAL PRIMARY KEY,
                code VARCHAR(20) NOT NULL UNIQUE,
                title VARCHAR(200) NOT NULL,
                context TEXT NOT NULL,
                level_id SMALLINT NOT NULL REFERENCES levels(id) ON UPDATE CASCADE,
                category scenario_category NOT NULL,
                prompt_template TEXT NOT NULL,
                character_name VARCHAR(100) NOT NULL,
                character_voice VARCHAR(50) NOT NULL DEFAULT 'alloy',
                duration_estimate SMALLINT NOT NULL CHECK (duration_estimate > 0),
                base_xp SMALLINT NOT NULL CHECK (base_xp > 0),
                is_active BOOLEAN NOT NULL DEFAULT true,
                play_count INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ
            )
            SQL);
        $this->addSql('CREATE INDEX idx_scenarios_level_id ON scenarios(level_id)');
        $this->addSql('CREATE INDEX idx_scenarios_category ON scenarios(category)');
        $this->addSql('CREATE INDEX idx_scenarios_is_active ON scenarios(is_active)');

        $this->addSql(<<<'SQL'
            CREATE TABLE sessions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                scenario_id INTEGER NOT NULL REFERENCES scenarios(id),
                score NUMERIC(5, 2) CHECK (score BETWEEN 0 AND 100),
                xp_earned INTEGER NOT NULL DEFAULT 0 CHECK (xp_earned >= 0),
                duration_seconds INTEGER CHECK (duration_seconds >= 0),
                status session_status NOT NULL DEFAULT 'in_progress',
                started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                ended_at TIMESTAMPTZ,
                CHECK (ended_at IS NULL OR ended_at >= started_at)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_sessions_user_id ON sessions(user_id)');
        $this->addSql('CREATE INDEX idx_sessions_scenario_id ON sessions(scenario_id)');
        $this->addSql('CREATE INDEX idx_sessions_status ON sessions(status)');
        $this->addSql('CREATE INDEX idx_sessions_started_at ON sessions(started_at DESC)');

        $this->addSql(<<<'SQL'
            CREATE TABLE session_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                session_id BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
                role message_role NOT NULL,
                content TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            SQL);
        $this->addSql('CREATE INDEX idx_session_messages_session_id ON session_messages(session_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                body TEXT NOT NULL,
                headers TEXT NOT NULL,
                queue_name VARCHAR(190) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
            )
            SQL);
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE session_messages');
        $this->addSql('DROP TABLE sessions');
        $this->addSql('DROP TABLE scenarios');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE levels');
        $this->addSql('DROP TABLE messenger_messages');

        $this->addSql('DROP TYPE scenario_category');
        $this->addSql('DROP TYPE message_role');
        $this->addSql('DROP TYPE session_status');
        $this->addSql('DROP TYPE user_role');
    }
}
