<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Oral placement test taken right after registration: placement_tests +
 * placement_test_messages. Reuses the existing session_status and
 * message_role enum types (identical shape, no need for new ones). Not part
 * of the original Jalon 3 MPD.
 */
final class Version20260907100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Placement test: placement_tests, placement_test_messages';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE placement_tests (
                id               BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id          BIGINT         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                status           session_status NOT NULL DEFAULT 'in_progress',
                result_level_id  SMALLINT       REFERENCES levels(id),
                started_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
                ended_at         TIMESTAMPTZ
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_placement_tests_user_id ON placement_tests(user_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE placement_test_messages (
                id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                placement_test_id   BIGINT       NOT NULL REFERENCES placement_tests(id) ON DELETE CASCADE,
                role                message_role NOT NULL,
                content             TEXT         NOT NULL,
                created_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
            )
            SQL);
        $this->addSql('CREATE INDEX idx_placement_test_messages_test_id ON placement_test_messages(placement_test_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE placement_test_messages');
        $this->addSql('DROP TABLE placement_tests');
    }
}
