<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * V2 pilot (Monde 1 "Vie quotidienne"): worlds, rooms, situations, missions,
 * mission_sessions, mission_messions - a purely additive extension of the
 * existing schema (LinguaBot_V2_Conception.md), reusing the message_role and
 * session_status enum types already created in the Milestone 1 migration.
 * No existing table is altered.
 */
final class Version20260916100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'V2 pilot: worlds, rooms, situations, missions, mission_sessions, mission_messages';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE worlds (
                id SERIAL PRIMARY KEY,
                code VARCHAR(20) NOT NULL UNIQUE,
                title VARCHAR(200) NOT NULL,
                description TEXT,
                order_num SMALLINT NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT true
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE rooms (
                id SERIAL PRIMARY KEY,
                world_id INTEGER NOT NULL REFERENCES worlds(id),
                code VARCHAR(20) NOT NULL UNIQUE,
                title VARCHAR(200) NOT NULL,
                background_image_src VARCHAR(255),
                order_num SMALLINT NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT true
            )
            SQL);
        $this->addSql('CREATE INDEX idx_rooms_world_id ON rooms(world_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE situations (
                id SERIAL PRIMARY KEY,
                room_id INTEGER NOT NULL REFERENCES rooms(id),
                code VARCHAR(20) NOT NULL UNIQUE,
                title VARCHAR(200) NOT NULL,
                description TEXT,
                order_num SMALLINT NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT true
            )
            SQL);
        $this->addSql('CREATE INDEX idx_situations_room_id ON situations(room_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE missions (
                id SERIAL PRIMARY KEY,
                situation_id INTEGER NOT NULL REFERENCES situations(id),
                level_id SMALLINT NOT NULL REFERENCES levels(id),
                code VARCHAR(20) NOT NULL UNIQUE,
                title VARCHAR(200) NOT NULL,
                objective TEXT NOT NULL,
                prompt_template TEXT NOT NULL,
                character_name VARCHAR(100) NOT NULL,
                character_voice VARCHAR(50) NOT NULL DEFAULT 'alloy',
                base_xp SMALLINT NOT NULL CHECK (base_xp > 0),
                order_num SMALLINT NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT true
            )
            SQL);
        $this->addSql('CREATE INDEX idx_missions_situation_id ON missions(situation_id)');
        $this->addSql('CREATE INDEX idx_missions_level_id ON missions(level_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE mission_sessions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                mission_id INTEGER NOT NULL REFERENCES missions(id),
                xp_earned INTEGER NOT NULL DEFAULT 0 CHECK (xp_earned >= 0),
                status session_status NOT NULL DEFAULT 'in_progress',
                started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                ended_at TIMESTAMPTZ,
                summary_data JSONB,
                CHECK (ended_at IS NULL OR ended_at >= started_at)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_mission_sessions_user_id ON mission_sessions(user_id)');
        $this->addSql('CREATE INDEX idx_mission_sessions_mission_id ON mission_sessions(mission_id)');
        $this->addSql('CREATE INDEX idx_mission_sessions_status ON mission_sessions(status)');

        $this->addSql(<<<'SQL'
            CREATE TABLE mission_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                mission_session_id BIGINT NOT NULL REFERENCES mission_sessions(id) ON DELETE CASCADE,
                role message_role NOT NULL,
                content TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            SQL);
        $this->addSql('CREATE INDEX idx_mission_messages_mission_session_id ON mission_messages(mission_session_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE mission_messages');
        $this->addSql('DROP TABLE mission_sessions');
        $this->addSql('DROP TABLE missions');
        $this->addSql('DROP TABLE situations');
        $this->addSql('DROP TABLE rooms');
        $this->addSql('DROP TABLE worlds');
    }
}
