<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Audit A5: challenge_messages - persists the Daily Challenge conversation
 * server-side, the same way session_messages already does for scenario
 * sessions, instead of trusting a client-supplied `history` array on every
 * message()/hint() call (see DailyChallengeController).
 */
final class Version20260914090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Audit A5: challenge_messages table, mirroring session_messages';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE challenge_messages (
                id                    BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                challenge_session_id  BIGINT      NOT NULL REFERENCES challenge_sessions(id) ON DELETE CASCADE,
                role                  message_role NOT NULL,
                content               TEXT        NOT NULL,
                created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            SQL);
        $this->addSql('CREATE INDEX idx_challenge_messages_challenge_session_id ON challenge_messages(challenge_session_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE challenge_messages');
    }
}
