<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Drops the v1.1 scenario catalog (scenarios, sessions, session_messages),
 * fully replaced on this branch by the V2 Adventure hierarchy
 * (worlds/rooms/situations/missions/mission_sessions/mission_messages from
 * Version20260916100000). session_status and message_role are left in
 * place: mission_sessions/mission_messages still use them.
 *
 * challenge_sessions.session_id (Version20260904150000) is dropped first -
 * a nullable FK to sessions that ChallengeSession never actually mapped
 * (confirmed unused in the entity and unreferenced anywhere else), left
 * over from early development before the Daily Challenge got its own
 * fully independent tables.
 */
final class Version20260917090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Drop the v1.1 scenario catalog (scenarios, sessions, session_messages), replaced by the V2 Adventure hierarchy';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE challenge_sessions DROP COLUMN session_id');
        $this->addSql('DROP TABLE session_messages');
        $this->addSql('DROP TABLE sessions');
        $this->addSql('DROP TABLE scenarios');
        $this->addSql('DROP TYPE scenario_category');
    }

    public function down(Schema $schema): void
    {
        $this->addSql("CREATE TYPE scenario_category AS ENUM ('quotidien', 'thematique')");

        $this->addSql(<<<'SQL'
            CREATE TABLE scenarios (
                id SERIAL PRIMARY KEY,
                code VARCHAR(20) NOT NULL UNIQUE,
                title VARCHAR(200) NOT NULL,
                context TEXT NOT NULL,
                level_id SMALLINT NOT NULL REFERENCES levels(id) ON UPDATE CASCADE,
                category scenario_category NOT NULL,
                prompt_template TEXT NOT NULL,
                character_name VARCHAR(100) NOT NULL,
                character_voice VARCHAR(50) NOT NULL DEFAULT 'alloy',
                duration_estimate SMALLINT NOT NULL CHECK (duration_estimate > 0),
                base_xp SMALLINT NOT NULL CHECK (base_xp > 0),
                is_active BOOLEAN NOT NULL DEFAULT true,
                play_count INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ
            )
            SQL);
        $this->addSql('CREATE INDEX idx_scenarios_level_id ON scenarios(level_id)');
        $this->addSql('CREATE INDEX idx_scenarios_category ON scenarios(category)');
        $this->addSql('CREATE INDEX idx_scenarios_is_active ON scenarios(is_active)');

        $this->addSql(<<<'SQL'
            CREATE TABLE sessions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                scenario_id INTEGER NOT NULL REFERENCES scenarios(id),
                score NUMERIC(5, 2) CHECK (score BETWEEN 0 AND 100),
                xp_earned INTEGER NOT NULL DEFAULT 0 CHECK (xp_earned >= 0),
                duration_seconds INTEGER CHECK (duration_seconds >= 0),
                status session_status NOT NULL DEFAULT 'in_progress',
                started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                ended_at TIMESTAMPTZ,
                CHECK (ended_at IS NULL OR ended_at >= started_at)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_sessions_user_id ON sessions(user_id)');
        $this->addSql('CREATE INDEX idx_sessions_scenario_id ON sessions(scenario_id)');
        $this->addSql('CREATE INDEX idx_sessions_status ON sessions(status)');
        $this->addSql('CREATE INDEX idx_sessions_started_at ON sessions(started_at DESC)');

        $this->addSql(<<<'SQL'
            CREATE TABLE session_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                session_id BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
                role message_role NOT NULL,
                content TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            SQL);
        $this->addSql('CREATE INDEX idx_session_messages_session_id ON session_messages(session_id)');

        $this->addSql('ALTER TABLE challenge_sessions ADD COLUMN session_id BIGINT REFERENCES sessions(id)');
    }
}
